# Copyright 2018 Dematic, Corp.
# Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: {{  .Release.Service  }}
    release: {{  .Release.Name  }}
    chart: {{  .Chart.Name  }}-{{  .Chart.Version | replace "+" "_"  }}
    app: {{  .Chart.Name  }}
    component: backend
    application: truck-alert
    service: generator
  name: {{  .Release.Name  }}-svc
spec:
  ports:
    - name: generator
      port: 80
      targetPort: rest
  selector:
    application: truck-alert
    service: generator
